language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"
install:
  - pip install .
  - mhcflurry-downloads fetch models_class1
script:
  - python tests/test___init__.py
  - python tests/test_transcript.py
