language: python
python:
  - "2.7"
  - "3.6"
  - "3.7"
install:
  - pip install .
  - mhcflurry-downloads fetch models_class1
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
    else
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - source "$HOME/miniconda/etc/profile.d/conda.sh"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - conda install -c bioconda samtools
script:
  - python tests/test___init__.py
  - python tests/test_transcript.py
